import type { ArchetypeProfile } from "../types"

export const ARCHETYPE_PROFILES: Record<string, ArchetypeProfile> = {
  ARCH_01: {
    id: "ARCH_01",
    name: "The Hero (Người Hùng)",
    coreDesire: "Chứng minh giá trị thông qua hành động dũng cảm.",
    clothing_style: "Trang phục chiến đấu, giáp nhẹ, thiết kế năng động, dễ di chuyển.",
    color_palette: ["#E11D48", "#F59E0B", "#111827"],
    famousCharacters: ["Tanjiro Kamado", "Midoriya Izuku", "Eren Yeager", "Son Goku"],
  },
  ARCH_02: {
    id: "ARCH_02",
    name: "The Rebel (Kẻ Nổi Loạn)",
    coreDesire: "Phá vỡ các quy tắc và phá hủy những thứ không hiệu quả.",
    clothing_style: "Trang phục bụi bặm, da thuộc, đinh tán, phong cách punk hoặc tối màu phá cách.",
    color_palette: ["#000000", "#7F1D1D", "#4B5563"],
    famousCharacters: ["Sasuke Uchiha", "Lelouch vi Britannia", "Sukuna", "Hiei"],
  },
  ARCH_03: {
    id: "ARCH_03",
    name: "The Sage (Nhà Thông Thái)",
    coreDesire: "Tìm kiếm chân lý và thấu hiểu thế giới.",
    clothing_style: "Áo choàng dài, trang phục truyền thống hoặc học giả, phụ kiện mang tính biểu tượng.",
    color_palette: ["#1E3A8A", "#D97706", "#F3F4F6"],
    famousCharacters: ["Jiraiya", "Satoru Gojo", "Sousuke Aizen", "Orochimaru"],
  },
  ARCH_04: {
    id: "ARCH_04",
    name: "The Innocent (Người Ngây Thơ)",
    coreDesire: "Trải nghiệm thiên đường, mong muốn hạnh phúc bình dị.",
    clothing_style: "Trang phục màu pastel, váy xòe, nhiều nơ hoặc thiết kế đơn giản, đáng yêu.",
    color_palette: ["#FBCFE8", "#BAE6FD", "#FEF08A"],
    famousCharacters: ["Anya Forger", "Nahida", "Eri", "Madoka Kaname"],
  },
  ARCH_05: {
    id: "ARCH_05",
    name: "The Jester (Kẻ Pha Trò)",
    coreDesire: "Sống trọn vẹn từng khoảnh khắc, tận hưởng niềm vui.",
    clothing_style: "Trang phục sặc sỡ, họa tiết bất đối xứng, độc lạ và mang tính biểu diễn.",
    color_palette: ["#9333EA", "#10B981", "#F59E0B"],
    famousCharacters: ["Gintoki Sakata", "Hisoka Morow", "Buggy", "Koro-sensei"],
  },
  ARCH_06: {
    id: "ARCH_06",
    name: "The Caregiver (Người Chăm Sóc)",
    coreDesire: "Bảo vệ và quan tâm đến những người xung quanh.",
    clothing_style: "Trang phục mang cảm giác mềm mại, tạp dề, đồng phục y tế hoặc đồ bảo hộ nhẹ.",
    color_palette: ["#6EE7B7", "#F87171", "#FFFFFF"],
    famousCharacters: ["Bruno Bucciarati", "Itachi Uchiha", "Koushi Sugawara", "Rem"],
  },
  ARCH_07: {
    id: "ARCH_07",
    name: "The Explorer (Người Khám Phá)",
    coreDesire: "Tự do tìm hiểu thế giới và trải nghiệm cuộc sống.",
    clothing_style: "Trang phục sinh tồn, túi hộp, áo khoác dã chiến, phụ kiện du hành.",
    color_palette: ["#047857", "#B45309", "#78716C"],
    famousCharacters: ["Monkey D. Luffy", "Gon Freecss", "Kenshin Himura", "Kino"],
  },
  ARCH_08: {
    id: "ARCH_08",
    name: "The Lover (Người Tình)",
    coreDesire: "Đạt được sự gắn kết, thân mật và tình yêu.",
    clothing_style: "Trang phục tôn dáng, quyến rũ, chất liệu mềm mại như lụa, ren hoặc thiết kế thanh lịch.",
    color_palette: ["#BE185D", "#F472B6", "#4C1D95"],
    famousCharacters: ["Sanji", "Mikasa Ackerman", "Yuno Gasai", "Howl"],
  },
  ARCH_09: {
    id: "ARCH_09",
    name: "The Creator (Người Sáng Tạo)",
    coreDesire: "Tạo ra những thứ có giá trị trường tồn.",
    clothing_style: "Trang phục lấm lem dầu mỡ, áo khoác lab, hoặc phong cách avant-garde nghệ thuật.",
    color_palette: ["#0284C7", "#EA580C", "#A3E635"],
    famousCharacters: ["Senku Ishigami", "Deidara", "Bulma", "Sasori"],
  },
  ARCH_10: {
    id: "ARCH_10",
    name: "The Ruler (Người Trị Vì)",
    coreDesire: "Kiểm soát và tạo ra trật tự cho thế giới.",
    clothing_style: "Trang phục hoàng gia, giáp trụ nặng, đính đá quý, áo choàng uy nghi.",
    color_palette: ["#B91C1C", "#FBBF24", "#1F2937"],
    famousCharacters: ["Rimuru Tempest", "Gilgamesh", "Frieza", "Saber"],
  },
  ARCH_11: {
    id: "ARCH_11",
    name: "The Magician (Nhà Phép Thuật)",
    coreDesire: "Hiểu biết quy luật vận hành của vũ trụ để biến đổi nó.",
    clothing_style: "Trang phục giả kim, áo choàng pháp sư có mũ trùm, nhiều ký tự chú thuật.",
    color_palette: ["#581C87", "#064E3B", "#000000"],
    famousCharacters: ["Edward Elric", "Geto Suguru", "Megumin", "Merlin"],
  },
  ARCH_12: {
    id: "ARCH_12",
    name: "The Everyman (Người Thường)",
    coreDesire: "Thuộc về một nơi nào đó, hòa nhập với mọi người.",
    clothing_style: "Trang phục đời thường, đồng phục học sinh tiêu chuẩn, thiết kế cơ bản không quá nổi bật.",
    color_palette: ["#64748B", "#9CA3AF", "#E5E7EB"],
    famousCharacters: ["Rock Lee", "Shinpachi Shimura", "Krillin", "Usopp"],
  },
}
