-- CosMate BE: Shipping address abstraction schema
-- Run on backend database. FE stores province_code + ward_code via API.

-- ---------------------------------------------------------------------------
-- 1. User address (core — no GHN IDs)
-- ---------------------------------------------------------------------------
ALTER TABLE user_address ADD COLUMN IF NOT EXISTS province_code INT;
ALTER TABLE user_address ADD COLUMN IF NOT EXISTS ward_code INT;
ALTER TABLE user_address ADD COLUMN IF NOT EXISTS internal_loc_code VARCHAR(32);
ALTER TABLE user_address ADD COLUMN IF NOT EXISTS province_name VARCHAR(255);
ALTER TABLE user_address ADD COLUMN IF NOT EXISTS ward_name VARCHAR(255);
ALTER TABLE user_address ADD COLUMN IF NOT EXISTS detail_address VARCHAR(500);

-- Legacy columns (keep during migration): city, district, address
-- city -> province_name, district -> ward_name, address -> detail_address

CREATE INDEX IF NOT EXISTS idx_user_address_internal_loc ON user_address(internal_loc_code);
CREATE INDEX IF NOT EXISTS idx_user_address_province_ward ON user_address(province_code, ward_code);

-- ---------------------------------------------------------------------------
-- 2. Order address snapshot
-- ---------------------------------------------------------------------------
ALTER TABLE order_address ADD COLUMN IF NOT EXISTS province_code INT;
ALTER TABLE order_address ADD COLUMN IF NOT EXISTS ward_code INT;
ALTER TABLE order_address ADD COLUMN IF NOT EXISTS internal_loc_code VARCHAR(32);
ALTER TABLE order_address ADD COLUMN IF NOT EXISTS province_name VARCHAR(255);
ALTER TABLE order_address ADD COLUMN IF NOT EXISTS ward_name VARCHAR(255);
ALTER TABLE order_address ADD COLUMN IF NOT EXISTS detail_address VARCHAR(500);

-- ---------------------------------------------------------------------------
-- 3. GHN mapping (provider-isolated)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ghn_address_mapping (
  id                  BIGSERIAL PRIMARY KEY,
  province_code       INT NOT NULL,
  ward_code           INT NOT NULL,
  internal_loc_code   VARCHAR(32) NOT NULL,
  province_name_system VARCHAR(255),
  ward_name_system     VARCHAR(255),
  ghn_province_id     INT NOT NULL,
  ghn_district_id     INT NOT NULL,
  ghn_ward_code       VARCHAR(20) NOT NULL,
  ghn_province_name   VARCHAR(255),
  ghn_district_name   VARCHAR(255),
  ghn_ward_name       VARCHAR(255),
  match_quality       VARCHAR(20) NOT NULL DEFAULT 'EXACT',
  source              VARCHAR(20) NOT NULL DEFAULT 'AUTO',
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (province_code, ward_code),
  UNIQUE (internal_loc_code),
  UNIQUE (ghn_district_id, ghn_ward_code)
);

-- ---------------------------------------------------------------------------
-- 4. Multi-provider (future)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shipping_provider (
  code VARCHAR(20) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  active BOOLEAN DEFAULT TRUE
);

INSERT INTO shipping_provider (code, name) VALUES ('GHN', 'Giao Hàng Nhanh')
ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS shipping_address_mapping (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_code VARCHAR(20) NOT NULL REFERENCES shipping_provider(code),
  province_code INT NOT NULL,
  ward_code INT NOT NULL,
  internal_loc_code VARCHAR(32) NOT NULL,
  provider_province_id VARCHAR(50),
  provider_district_id VARCHAR(50),
  provider_ward_code VARCHAR(50),
  provider_meta JSONB,
  match_quality VARCHAR(20) NOT NULL,
  source VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (provider_code, province_code, ward_code)
);

-- ---------------------------------------------------------------------------
-- 5. GHN master data cache
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ghn_master_province (
  province_id INT PRIMARY KEY,
  province_name VARCHAR(255),
  synced_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS ghn_master_district (
  district_id INT PRIMARY KEY,
  province_id INT NOT NULL,
  district_name VARCHAR(255),
  synced_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS ghn_master_ward (
  ward_code VARCHAR(20) PRIMARY KEY,
  district_id INT NOT NULL,
  ward_name VARCHAR(255),
  synced_at TIMESTAMPTZ
);
