// src/constants/resources.ts

export type Language = 'VI' | 'EN' | 'JA';

export const RESOURCES = {
  VI: {
    welcomeBack: 'Chào mừng trở lại CosMate',
    joinCommunity: 'Tham gia cộng đồng CosMate',
    loginDesc: 'Đăng nhập để tiếp tục hành trình cosplay',
    signupDesc: 'Tạo tài khoản để bắt đầu hành trình cosplay',
    chooseRole: 'Chọn vai trò của bạn',
    renter: 'Tôi muốn Thuê',
    renterDesc: 'Tìm & thuê trang phục',
    lender: 'Tôi muốn Cho thuê',
    lenderDesc: 'Đăng đồ & kiếm tiền',
    google: 'Tiếp tục với Google',
    facebook: 'Tiếp tục với Facebook',
    orEmail: 'Hoặc tiếp tục bằng email',
    fullName: 'Họ và tên',
    enterName: 'Nhập họ tên của bạn',
    emailAddr: 'Địa chỉ Email',
    enterEmail: 'Nhập email của bạn',
    password: 'Mật khẩu',
    enterPass: 'Nhập mật khẩu của bạn',
    forgotPass: 'Quên mật khẩu?',
    agree: 'Tôi đồng ý với',
    terms: 'Điều khoản dịch vụ',
    and: 'và',
    privacy: 'Chính sách bảo mật',
    loginBtn: 'Đăng nhập',
    createBtn: 'Tạo tài khoản',
    noAccount: "Chưa có tài khoản?",
    haveAccount: "Đã có tài khoản?",
    signupLink: 'Đăng ký',
    loginLink: 'Đăng nhập',
    langName: 'Tiếng Việt'
  },
  EN: {
    welcomeBack: 'Welcome back to CosMate',
    joinCommunity: 'Join the CosMate Community',
    loginDesc: 'Login to continue your cosplay journey',
    signupDesc: 'Create an account to start your cosplay journey',
    chooseRole: 'Choose your role',
    renter: 'I want to Rent',
    renterDesc: 'Browse & rent costumes',
    lender: 'I want to Lend',
    lenderDesc: 'List & earn from costumes',
    google: 'Continue with Google',
    facebook: 'Continue with Facebook',
    orEmail: 'Or continue with email',
    fullName: 'Full Name',
    enterName: 'Enter your full name',
    emailAddr: 'Email Address',
    enterEmail: 'Enter your email',
    password: 'Password',
    enterPass: 'Enter your password',
    forgotPass: 'Forgot password?',
    agree: 'I agree to the',
    terms: 'Terms of Service',
    and: 'and',
    privacy: 'Privacy Policy',
    loginBtn: 'Login',
    createBtn: 'Create Account',
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    signupLink: 'Sign up',
    loginLink: 'Login',
    langName: 'English'
  },
  JA: {
    welcomeBack: 'CosMateへようこそ',
    joinCommunity: 'CosMateコミュニティに参加',
    loginDesc: 'コスプレの旅を続けるにはログインしてください',
    signupDesc: 'アカウントを作成して旅を始めましょう',
    chooseRole: '役割を選択してください',
    renter: '借りたい',
    renterDesc: '衣装を探してレンタル',
    lender: '貸したい',
    lenderDesc: '衣装を出品して収益化',
    google: 'Googleで続ける',
    facebook: 'Facebookで続ける',
    orEmail: 'またはメールで続ける',
    fullName: '氏名',
    enterName: '氏名を入力してください',
    emailAddr: 'メールアドレス',
    enterEmail: 'メールアドレスを入力',
    password: 'パスワード',
    enterPass: 'パスワードを入力',
    forgotPass: 'パスワードを忘れた場合',
    agree: '私はこれに同意します：',
    terms: '利用規約',
    and: 'および',
    privacy: 'プライバシーポリシー',
    loginBtn: 'ログイン',
    createBtn: 'アカウント作成',
    noAccount: "アカウントをお持ちでないですか？",
    haveAccount: "すでにアカウントをお持ちですか？",
    signupLink: '新規登録',
    loginLink: 'ログイン',
    langName: '日本語'
  }
};